_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "checkpoints/vaipe/model_reset_surgery.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NUM_CLASSES: 262
    FREEZE_FEAT: False
  BACKBONE:
    FREEZE: False
  PROPOSAL_GENERATOR:
    FREEZE: False
DATASETS:
  TRAIN: ('vaipe_train_all_13shot',)
  TEST: ('vaipe_test_all',)
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.001
  STEPS: (10000,15000)
  MAX_ITER: 20000
  CHECKPOINT_PERIOD: 5000
  WARMUP_ITERS: 100
OUTPUT_DIR: "checkpoints/vaipe/TFA_fastercnn_r50_ft_13shot"