_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  META_ARCHITECTURE: "RCNN_SGRN_COPY"
  # WEIGHTS: "/home/huyen/projects/huyen/Test1/FSCE/FSCE/checkpoints/vaipe/faster_rcnn/R_50_FPN_all/test2705/model_0029999.pth"
  # WEIGHTS: "/home/huyen/projects/huyen/Test1/FSCE/test_SRGN/FSCE/checkpoints/vaipe/FRCNN/R_50_FPN_all/test3005/model_0059999.pth"
  # WEIGHTS: "/home/huyen/projects/huyen/Test1/FSCE/test_SRGN/FSCE/checkpoints/vaipe/FRCNN/R_50_FPN_all/test0506/model_0059999.pth"
  # WEIGHTS: "checkpoints/R-50.pkl"
  # WEIGHTS: "/home/huyen/projects/huyen/Test1/FSCE/test_SRGN/FSCE/checkpoints/test/model_0034999.pth"
  # WEIGHTS: "/home/huyen/projects/huyen/Test1/FSCE/test_SRGN/FSCE/checkpoints/test_sgrn/model_0059999.pth"
  WEIGHTS: "/home/huyen/projects/FSCE/checkpoints/vaipe_duy/srgn/model_0059999.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NUM_CLASSES: 96
    # NAME: StandardROIHeads_Copy2
    NAME: StandardROIHeads_Copy2
    BATCH_SIZE_PER_IMAGE: 128
    FREEZE_FEAT: True
  RPN:
    POST_NMS_TOPK_TEST: 128
  BACKBONE:
    FREEZE: True
    FREEZE_P5: True
  PROPOSAL_GENERATOR:
    FREEZE: True
DATASETS:
  TRAIN: ('vaipe_train_duy',)
  TEST: ('vaipe_test_duy',)  
SOLVER:
  IMS_PER_BATCH: 4
  STEPS: (10000, 20000)
  MAX_ITER: 60000
  CHECKPOINT_PERIOD: 5000
OUTPUT_DIR: "checkpoints/test_sgrn_rand/"
