_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  # WEIGHTS: "/home/huyen/projects/huyen/Test1/FSCE/FSCE/checkpoints/vaipe/faster_rcnn/R_50_FPN_all/test2705/model_0029999.pth"
  # WEIGHTS: "/home/huyen/projects/huyen/Test1/FSCE/test_SRGN/FSCE/checkpoints/vaipe/FRCNN/R_50_FPN_all/test3005/model_0059999.pth"
  WEIGHTS: "/home/huyen/projects/FSCE/checkpoints/vaipe/faster_rcnn/R_50_FPN_all/test2705/model_0029999.pth"
  # WEIGHTS: "checkpoints/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NUM_CLASSES: 262
    NAME: StandardROIHeads2
    BATCH_SIZE_PER_IMAGE: 128
  RPN:
    POST_NMS_TOPK_TEST: 128
DATASETS:
  TRAIN: ('vaipe_train',) #('coco_2014_train',) #
  TEST: ('vaipe_test',) #('coco_2014_val',)  #
SOLVER:
  IMS_PER_BATCH: 4
  STEPS: (10000, 20000)
  MAX_ITER: 60000
  CHECKPOINT_PERIOD: 5000
OUTPUT_DIR: "checkpoints/vaipe/FRCNN/R_50_FPN_all/test0506"
